update dockerization
floatingpoints/backend pull request #1
Opened 2023-01-08 18:30 UTC by harrytang

fixes typo and use postgres

2023-01-08 20:13 UTC, nlhkh requested changes

2023-01-08 20:13 UTC, nlhkh commented on docker-compose.yaml
> +    image: postgres:15
Use `postgis/postgis:15-3.3-alpine`. We may need to use the Map interface in Directus, which requires Postgis

2023-01-08 20:30 UTC, harrytang commented on docker-compose.yaml
> +    image: postgres:15
postgis does not support arm officially, but I think we can use  this forked images https://github.com/baosystems/docker-postgis

2023-01-09 19:08 UTC, nlhkh approved these changes

2023-01-09 19:08 UTC, merged